server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval = true
    username: root
    password: 123456789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
#logging:
#  level:
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 918 029-17-75
  email: gluhenko78@mail.ru
  copyright: Алексей Глущенко
  copyrightFrom: 2021
  # minutes
config:
  Captcha:
    StorageTime: 60
    Height: 35
    Width: 100
  uploadFile: /home/alexey/uploads